import csv
import argparse
import sys
import os
import pandas as pd

def extract_csv_data(file_path):
    _, ext = os.path.splitext(file_path)
    
    if ext.lower() in ['.xlsx', '.xls']:
        try:
            csv_file_path = f"{os.path.splitext(file_path)[0]}.csv"
            df = pd.read_excel(file_path)
            df.to_csv(csv_file_path, index=False)
            file_path = csv_file_path
        except Exception as e:
            print(f"Error converting {file_path} to CSV: {e}")
            sys.exit(1)

    data = []
    try:    
        with open(file_path, mode='r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                data.append(row)
        return data
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        sys.exit(1)

def remove_comments(table):
    for row in table:
        row.pop('Comment', None)
        row.pop('Column1', None)
    return table

def sort_table(table):
    if not table:
        return table
    first_col_key = list(table[0].keys())[0]
    return sorted(table, key=lambda x: x[first_col_key])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Extract data from two CSV files.")
    parser.add_argument("-orig", "--original", required=True, help="Path to the original Excel or CSV file.")
    parser.add_argument("-new", "--new", required=True, help="Path to the new CSV generated by moo.py.")
    
    args = parser.parse_args()

    original = extract_csv_data(args.original)
    original = remove_comments(original)
    original = sort_table(original)

    new = extract_csv_data(args.new)
    new = remove_comments(new)
    new = sort_table(new)

    num_rows = min(len(original), len(new))
    num_cols = min(len(original[0]), len(new[0]))

    if num_rows == 0 or num_cols == 0:
        print("One of the files is empty.")
        sys.exit(1)

    col_metrics = {}
    
    
    total_rel_err = 0.0

    accurate_cells = 0
    acc_tol = 0.05

    valid_cells = 0

    for col in range(1, num_cols):
        col_rel_err = 0
        col_abs_err = 0
        col_max_err = 0

        skipped = 0
        orig_name = list(original[0].keys())[col]
        new_name = list(new[0].keys())[col]

        if orig_name != new_name:
            print(f"Column names are not the same (col {col + 1}): '{orig_name}' vs '{new_name}'")
            sys.exit(1)

        for row in range(num_rows):
            orig_value = original[row][orig_name]
            new_value = new[row][new_name]
            if new_value == '' and orig_value != '':
                print(f"Missing value in new file at row {row + 1}, column '{new_name}'")
                sys.exit(1)
            if orig_value == '--undefined--' or new_value == '--undefined--':
                skipped += 1
                continue
            orig_value = float(orig_value)
            new_value = float(new_value)
            if new_value == 0 and orig_value == 0:
                skipped += 1
                continue
            diff = abs(float(orig_value) - float(new_value))
            rel_err = abs(diff / new_value) if float(new_value) else float('1')
            col_rel_err += rel_err
            col_abs_err += diff
            col_max_err = max(col_max_err, rel_err)
            valid_cells += 1
            if rel_err <= acc_tol:
                accurate_cells += 1

        total_rel_err += col_rel_err
        avg_rel_err = col_rel_err / (num_rows - skipped)
        mae = col_abs_err / (num_rows - skipped)


        col_metrics[orig_name] = {
            'avg_rel_err': avg_rel_err,
            'mae': mae,
            'max_rel_err': col_max_err,
        }

last_folder = os.path.basename(os.path.dirname(os.path.abspath(args.original)))

header_format = "{:<30} | {:<15} | {:<15} | {:<15}"
row_format = "{:<30} | {:<15.5f} | {:<15.5f} | {:<15.5f}"

output_lines = []

output_lines.append(f"\n[{last_folder}]")
output_lines.append("=" * 85)
output_lines.append(header_format.format("Column Name", "Avg Rel Error", "Max Rel Error", "Mean Abs Err (MAE)"))
output_lines.append("-" * 85)

for col_name, metrics in col_metrics.items():
    display_name = col_name if len(col_name) <= 30 else col_name[:27] + "..."
    output_lines.append(row_format.format(
        display_name, 
        metrics['avg_rel_err'], 
        metrics['max_rel_err'], 
        metrics['mae']
    ))
output_lines.append("=" * 85)

output_lines.append("\n" + "=" * 45)
output_lines.append(f"{'GLOBAL TABLE METRICS':^45}")
output_lines.append("=" * 45)

if valid_cells > 0:
    table_avg_rel_err = total_rel_err / valid_cells
    table_accuracy = (accurate_cells / valid_cells) * 100
    
    output_lines.append(f"{'Total Valid Cells Evaluated:':<35} {valid_cells:,}")
    output_lines.append(f"{'Table-Wide Avg Rel Error:':<35} {table_avg_rel_err * 100:.2f}%")
    output_lines.append(f"{f'Table-Wide Accuracy (≤{acc_tol}):':<35} {table_accuracy:.2f}%")
else:
    output_lines.append(f"{'Status:':<35} No valid numeric cells found.")
    
output_lines.append("-" * 45)
output_lines.append(f"{'Evaluation Scope:':<35} {num_rows} rows x {num_cols} columns")
output_lines.append("=" * 45 + "\n")

# Combine list into a single string for printing and writing
output_text = "\n".join(output_lines)

# Output to console
print(output_text)

# Append to the chosen text file
with open('./results.txt', 'a', encoding='utf-8') as file:
    file.write(output_text)